const ProjectList = [
    {
        title : "Investigating Universal Min-Circle Sequence Binding Protein (UMSBP) as a Therapeutic Target for Leishmaniasis Drug Development",
        pi : "Dr. Prakash Saudagar",
        co_pi : null,
        funding_agency : "ANRF Year: 2024-2027",
        grant_amount : "63.50 Lakhs",
        status : "Ongoing",
    },
    {
        title : "Smart polymeric nanoparticles-based delivery system for the delivery of anti-tuberculosis drug",
        pi : "Prof. Shirish H Sonawane",
        co_pi : "Dr. Prakash Saudagar",
        funding_agency : "SPARC Year: 2013-25",
        grant_amount : "25.00 Lakhs",
        status : "Completed",
    },
    {
        title : "Characterization and validation of tyrosine aminotransferase from Leishmania donovani as a potential drug target",
        pi : "Dr. Prakash Saudagar",
        co_pi : null,
        funding_agency : "SERB Year: 2019-22",
        grant_amount : "47.12 Lakhs",
        status : "Completed",
    },
    {
        title : "Studies on Mitogen-activated protein kinase of Leishmania parasite as a therapeutic target",
        pi : "Dr. Prakash Saudagar",
        co_pi : null,
        funding_agency : "SERB (DST, Govt. of India), 2015-18",
        grant_amount : "20.9 Lakhs",
        status : "Completed",
    },
    {
        title : "Ultrasonic encapsulation of bioactive compounds to deliver in the food matrix",
        pi : "Prof. Shirish H Sonawane",
        co_pi : "Dr. Prakash Saudagar",
        funding_agency : "DST, Year: 2018-20",
        grant_amount : "15.7 Lakhs",
        status : "Completed",
    },
    {
        title : "Identification of novel drug candidates for leishmaniasis: Studies on redox enzymes of the parasite",
        pi : "Dr. Prakash Saudagar",
        co_pi : null,
        funding_agency : "NITW, Year: 2014-16",
        grant_amount : "5.0 Lakhs",
        status : "Completed",
    },
]
export default ProjectList;